name: 'git-mirror'
author: 'Thamognya Kodi'
description: 'Action for mirroring a repository in another location using SSH.'
branding:
  icon: 'copy'
  color: 'red'
inputs:
  source-repo:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
  destination-repo:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-repo }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.dry-run }}
